name: ML-31010
channels:
  - pytorch-nightly
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2022.10
  - alabaster=0.7.12
  - anaconda=custom
  - anyio=3.5.0
  - appdirs=1.4.4
  - appnope=0.1.2
  - appscript=1.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astroid=2.14.2
  - astropy=5.1
  - asttokens=2.0.5
  - astunparse=1.6.3
  - attrs=22.1.0
  - automat=20.2.0
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.1
  - bcrypt=3.2.0
  - beautifulsoup4=4.12.0
  - biopython=1.81
  - bitarray=2.5.1
  - bkcharts=0.2
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.3
  - bokeh=2.4.3
  - boltons=23.0.0
  - boto3=1.24.28
  - botocore=1.27.59
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - clyent=1.2.2
  - colorama=0.4.6
  - colorcet=3.0.1
  - comm=0.1.2
  - conda=23.3.1
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - constantly=15.1.0
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cssselect=1.1.0
  - curl=7.88.1
  - cycler=0.11.0
  - cython=0.29.33
  - cytoolz=0.12.0
  - dask=2023.3.2
  - dask-core=2023.3.2
  - datashader=0.14.4
  - datashape=0.5.4
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.6
  - distributed=2023.3.2
  - docutils=0.18.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - filelock=3.9.0
  - flask=2.2.2
  - flit-core=3.8.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - fsspec=2023.3.0
  - gensim=4.3.0
  - gettext=0.21.1
  - giflib=5.2.1
  - glew=2.1.0
  - glib=2.74.1
  - glib-tools=2.74.1
  - glm=0.9.9.4
  - gmp=6.2.1
  - gmpy2=2.1.2
  - greenlet=2.0.1
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - h5py=3.7.0
  - hdf4=4.2.13
  - hdf5=1.12.1
  - heapdict=1.0.1
  - holoviews=1.15.4
  - hvplot=0.8.2
  - hyperlink=21.0.0
  - icu=70.1
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.26.0
  - imagesize=1.4.1
  - importlib-metadata=6.0.0
  - incremental=21.3.0
  - iniconfig=1.1.1
  - intake=0.6.8
  - ipykernel=6.19.2
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.2
  - isort=5.9.3
  - itemadapter=0.3.0
  - itemloaders=1.0.4
  - itsdangerous=2.0.1
  - jdcal=1.4.1
  - jedi=0.18.1
  - jinja2=3.1.2
  - jmespath=0.10.0
  - joblib=1.1.1
  - jpeg=9e
  - jq=1.6
  - json5=0.9.6
  - jsonpatch=1.32
  - jsonpointer=2.1
  - jsonschema=4.17.3
  - jupyter_client=8.1.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=7.88.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.74.1
  - libiconv=1.17
  - libidn2=2.3.1
  - libllvm11=11.1.0
  - libllvm14=14.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.52.0
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.2
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzip=1.5.1
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - llvmlite=0.39.1
  - locket=1.0.0
  - lxml=4.9.2
  - lz4=3.1.3
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdtraj=1.9.7
  - mistune=0.8.4
  - mock=4.0.3
  - mpc=1.1.0
  - mpfr=4.0.2
  - msgpack-python=1.0.3
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nbclassic=0.5.4
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=2.8.4
  - nglview=3.0.3
  - nltk=3.7
  - nomkl=3.0
  - nose=1.3.7
  - notebook=6.5.3
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89
  - numba=0.56.4
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - numpydoc=1.5.0
  - olefile=0.46
  - oniguruma=6.9.7.1
  - openblas=0.3.21
  - openblas-devel=0.3.21
  - openjpeg=2.3.0
  - openpyxl=3.0.10
  - openssl=3.1.0
  - packaging=23.0
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - panel=0.14.3
  - param=1.12.3
  - parsel=1.6.0
  - parso=0.8.3
  - partd=1.2.0
  - patsy=0.5.3
  - pcre2=10.40
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=2.5.2
  - plotly=5.9.0
  - pluggy=1.0.0
  - ply=3.11
  - pmw=2.0.1
  - pooch=1.4.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - protego=0.1.16
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py=1.11.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycodestyle=2.10.0
  - pycosat=0.6.4
  - pycparser=2.21
  - pyct=0.5.0
  - pycurl=7.45.1
  - pydispatcher=2.0.5
  - pyerfa=2.0.0
  - pyflakes=3.0.1
  - pygments=2.11.2
  - pyhamcrest=2.0.2
  - pylint=2.16.2
  - pymol-open-source=2.5.0
  - pyodbc=4.0.34
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytables=3.7.0
  - pytest=7.1.2
  - python=3.10.10
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-snappy=0.6.1
  - python.app=3
  - python_abi=3.10
  - pytoolconfig=1.2.5
  - pytorch=2.1.0.dev20230412
  - pytz=2022.7
  - pyviz_comms=2.0.2
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.8
  - queuelib=1.5.0
  - readline=8.2
  - regex=2022.7.9
  - requests=2.28.1
  - requests-file=1.5.1
  - rope=1.7.0
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - ruamel_yaml=0.17.21
  - s3transfer=0.6.0
  - scikit-image=0.19.3
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - scrapy=2.8.0
  - seaborn=0.12.2
  - send2trash=1.8.0
  - service_identity=18.1.0
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - smart_open=5.2.1
  - snappy=1.1.9
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - sortedcollections=2.1.0
  - sortedcontainers=2.4.0
  - soupsieve=2.4
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlalchemy=1.4.39
  - sqlite=3.41.1
  - stack_data=0.2.0
  - statsmodels=0.13.5
  - sympy=1.11.1
  - tabulate=0.8.10
  - tbb=2021.8.0
  - tbb4py=2021.8.0
  - tblib=1.7.0
  - tenacity=8.0.1
  - terminado=0.17.1
  - testpath=0.6.0
  - threadpoolctl=2.2.0
  - tifffile=2021.7.2
  - tinycss2=1.2.1
  - tk=8.6.12
  - tldextract=3.2.0
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.1
  - toolz=0.12.0
  - torchaudio=2.1.0.dev20230412
  - torchvision=0.13.1
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - twisted=22.2.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2023c
  - unixodbc=2.3.11
  - urllib3=1.26.15
  - w3lib=1.21.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.2.3
  - wget=1.20.3
  - wheel=0.38.4
  - widgetsnbextension=3.6.0
  - wrapt=1.14.1
  - xarray=2022.11.0
  - xlrd=2.0.1
  - xlsxwriter=3.0.3
  - xlwings=0.29.1
  - xz=5.2.10
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zict=2.1.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zope=1.0
  - zope.interface=5.4.0
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - cattrs==22.2.0
      - docopt==0.6.2
      - esbonio==0.16.1
      - exceptiongroup==1.1.1
      - lsprotocol==2023.0.0a1
      - mpmath==1.2.1
      - pygls==1.0.1
      - pyspellchecker==0.7.1
      - typeguard==2.13.3
      - yarg==0.1.9